from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from schemas import StudyPlanRequest
from agent import study_agent

app = FastAPI(title="AI Study Companion Backend")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.post("/generate-plan")
async def generate_study_plan(request: StudyPlanRequest):
    try:
        prompt = f"""
        Subject: {request.subject}
        Level: {request.level}
        Hours per day: {request.hours_per_day}

        Generate a study plan and explain it in simple language.
        """

        response = await study_agent.run(prompt)

        clean_text = response.output if hasattr(response, "output") else str(response)
        return {
            "study_plan": clean_text,
            "explanation": "Generated by AI Study Companion"
            }


    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
